name: ecg_serial_monitor
version: 0.4.0
description: A flutter app to monitor ECG data from a serial port.
homepage: https://github.com/anuragdevon/reader_app

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^2.0.0-nullsafety.0
  cupertino_icons: ^1.0.3
  flutter_bluetooth_serial: ^0.4.0
  path_provider: ^2.0.11
  downloads_path_provider: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
